routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('auth','checkRole:admin')->group(function(){
    Route::get('/','AdminController@index')->name('index');
    Route::get('/users','AdminController@users')->name('user.index');
    Route::get('/user/{id}/edit','AdminController@edit')->name('user.edit');
    Route::get('/user/tambah','AdminController@tambah')->name('user.tambah');
    Route::post('user/tambah','AdminController@store')->name('user.store');
    Route::get('/user/{id}/delete','AdminController@delete')->name('user.delete');
    Route::get('/user/{id}','AdminController@show')->name('user.show');
    Route::put('/user/{id}','AdminController@update')->name('user.update');
    Route::get('/industri','IndustriController@index')->name('industri.index');
});

Route::namespace('User')->prefix('user')->name('user.')->middleware('auth','checkRole:user')->group(function(){
    Route::get('/','UserController@index')->name('index');
    Route::get('/industri/daftar','IndustriController@daftar')->name('industri.daftar');
    Route::post('industri/daftar','IndustriController@store')->name('industri.save');
});

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    //
    public function user()
    {
        return $this->hasMany('App\User');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected $attributes = [
        'role_id' => 2
    ];

    // one to many relationship
    public function role(){
        return $this->belongsTo('App\Role');
    }
    public function industri()
    {
        return $this->hasOne('App\User\Industry','id','industri_id');
    }
}

app/Http/Controllers/Admin/AdminController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\Http\Controllers\Controller;
use App\User;
use App\Role;
use Auth;

class AdminController extends Controller
{
    public function index()
    {
        return view('admin.index');
    }

    public function users()
    {
        $users = User::all();
        return view('admin.user.index')->with('users',$users);
    }

    public function edit($id)
    {
        $user = User::findOrFail($id);
        $roles = Role::all();
        // dd($user);
        return view('admin.user.edit')->with(['user'=>$user, 'roles'=>$roles]);
    }

    public function tambah(){
        return view('admin.user.tambah');
    }
    public function show($id)
    {
        $user = User::findOrFail($id);
        $roles = Role::all();
        // dd($user);
        return view('admin.user.edit')->with(['user'=>$user, 'roles'=>$roles]);
        
    }

    public function store(Request $request)
    {
        // $user = new User;
        // $user->name = $request->name;
        // $user->email = $request->email;
        // $user->password = bcrypt($request->password);
        return response()->json(['success'=>'Akun berhasil dibuat ']);

    }

    public function update($id,Request $request)
    {
        $request->validate([
            'name' => ['required'],
            'role' => ['required']
        ]);
        $user = User::findOrFail($id);
        $user->name = $request->name;
        $user->role_id = $request->role;
        $user->save();
        return redirect()->route('admin.user.index');
        
        // if($request->new_password !== null){
        //     if($user->password == bcrypt($request->old_password)){
        //         // $user->password = bcrypt($request->new_password);
        //         $user->password = $request->new_password;
        //     }
        // }
        // dd(Hash::check($request->new_password, bcrypt($user->password)));
        // dd($user, $request->new_password, bcrypt($request->new_password),bcrypt($request->old_password));
    }

    public function delete($id)
    {
        if (Auth::user()->id !== intval($id)) {
            $user = User::find($id);
            $user->delete();
            return redirect()->route('admin.users');
        }
        return redirect()->route('admin.users');
        
    }
    
}

app/Http/Controllers/Admin/IndustriController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User\Industry;

class IndustriController extends Controller
{
    //
    public function index()
    {
        # code...
        $industries = Industry::all();
        // dd($industries);
        return view('admin.industri.index')->with(['industries'=>$industries]);
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Auth;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {

        // $user = User::find(1);
        // dd($user->role->name);
        // dd(Auth::user()->role());
        return view('home');
    }
}

app/Http/Controllers/User/IndustriController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User\Industry;
use App\User;
use Auth;

class IndustriController extends Controller
{
    //
    public function daftar()
    {
        return view('user.industri.daftar');
    }

    public function store(Request $request)
    {
        $industri = new Industry($request->all());
        $industri->save();
        $user = User::find(Auth::user()->id);
        $user->industri_id = $industri->id;
        $user->save();
        return redirect()->route('user.index');

    }
}

app/Http/Controllers/User/UserController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User\Industri;
use Auth;

class UserController extends Controller
{
    //
    public function index()
    {
        // dd(Auth::user()->industri);
        $industri = Auth::user()->industri;
        // dd($industri);
        // dd(array_random(['tekstil','makanan','jasa']));
        return view('user.index')->with(['industri'=>$industri]);
    }
}

resources/views/admin/industri/index.blade.php
@extends('layouts.admin')
@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Dashboard</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Dashboard v1</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Main row -->
        <div class="row">
            <!-- Left col -->
            <section class="col-lg-12 col-sm-12 col-12">
                <!-- Custom tabs (Charts with tabs)-->
                <div class="card">
                    <div class="card-header justify-c">
                        <h3 class="card-title">
                            User
                        </h3>
                        <a class="btn btn-info btn-sm float-right" href="{{route('admin.user.tambah')}}"> + Tambah</a>

                    </div><!-- /.card-header -->
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover dataTable" role="grid"
                            aria-describedby="example2_info">
                            <thead>
                                <tr role="row">
                                    <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1"
                                        colspan="1" aria-sort="ascending" aria-label="#">#</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Nama Pemilik">
                                        Nama Pemilik</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Nama Usaha">
                                        Nama Usaha</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Email">
                                        Email</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="status">
                                        Status</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Action">
                                        Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($industries as $in)

                                <tr role="row">
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$in->nama_pemilik}}</td>
                                    <td>{{$in->nama_usaha}}</td>
                                    <td>{{$in->email}}</td>
                                    <td>
                                        @if ($in->status==1)
                                        <button class="btn btn-success btn-sm">Verified</button>
                                        @else
                                        <button class="btn btn-danger btn-sm">Unverified</button>
                                        @endif</td>
                                    <td><a class="btn btn-warning btn-sm"
                                            href="{{route('admin.user.edit',$in->id)}}">Edit</a>
                                        <a href="{{route('admin.user.delete',$in->id)}}"
                                            class="btn btn-danger btn-sm">Hapus</a></td>
                                </tr>
                                @endforeach

                            </tbody>
                        </table>
                    </div><!-- /.card-body -->
                </div>
                <!-- /.card -->




            </section>
            <!-- /.Left col -->
        </div>
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection
@section('script')
<script>
    $(function () {
    $("#example2").DataTable();
    $('#example1').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
  });
</script>
@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.admin')
@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Dashboard</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item active">Dashboard v1</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <!-- Main row -->
    <div class="row">
      <!-- Left col -->
      <section class="col-lg-12 col-sm-12 col-12">
        <!-- Custom tabs (Charts with tabs)-->
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Edit Profil</h3>
          </div>
          <!-- /.card-header -->
          <!-- form start -->
          <form method="POST" action="{{route('admin.user.update', $user->id)}}" class="form-horizontal">
            {{ csrf_field() }}
            @method('PUT')
            <div class="card-body">
              <div class="form-group row">
                <label for="inputName" class="col-sm-2 col-form-label">Nama</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="inputName" name="name" value="{{$user->name}}">
                </div>
              </div>
              <div class="form-group row">
                <label for="inputEmail" class="col-sm-2 col-form-label">Email</label>
                <div class="col-sm-10">
                  <input type="email" class="form-control" id="inputEmail" name="email" value="{{$user->email}}"
                    disabled>
                </div>
              </div>
              <div class="form-group row">
                <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label>
                <div class="col-sm-10">
                  <input type="password" class="form-control" id="inputPassword3" name="old_password"
                    placeholder="Old Password">
                </div>
              </div>
              <div class="form-group row">
                <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label>
                <div class="col-sm-10">
                  <input type="password" class="form-control" id="inputPassword3" name="new_password"
                    placeholder="New Password">
                </div>
              </div>

              <div class="form-group row">
                <label for="inputRole" class="col-sm-2 col-form-label">Role</label>
                <div class="col-sm-10">
                  <select name="role" class="form-control">
                    @foreach ($roles as $role)
                    <option value="{{$role->id}}" {{ $user->role->id === $role->id ? 'selected' : null }}>
                      {{$role->name}}
                    </option>
                    @endforeach
                  </select>
                </div>
              </div>

              <!-- /.card-body -->
              <div class="card-footer">
                <button type="submit" class="btn btn-primary float-right">Simpan</button>
              </div>
              <!-- /.card-footer -->
          </form>
        </div>
        {{-- card end --}}




      </section>
      <!-- /.Left col -->
    </div>
    <!-- /.row (main row) -->
  </div><!-- /.container-fluid -->
</section>
<!-- /.content -->

@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.admin')
@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Dashboard</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item active">Dashboard v1</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <!-- Main row -->
    <div class="row">
      <!-- Left col -->
      <section class="col-lg-12 col-sm-12 col-12">
        <!-- Custom tabs (Charts with tabs)-->
        <div class="card">
          <div class="card-header">
            <div class="d-flex justify-content-between align-items-center">
              <h3 class="card-title">
                User
              </h3>
              {{-- <a class="btn btn-info btn-sm float-right" href="{{route('admin.user.tambah')}}"> + Tambah</a> --}}
              <button type="button" class="btn btn-info btn-sm float-right" data-toggle="modal"
                data-target="#modal-tambah"> + Tambah</button>
            </div>

          </div><!-- /.card-header -->
          <div class="card-body">
            <table id="example2" class="table table-bordered table-hover dataTable" role="grid"
              aria-describedby="example2_info">
              <thead>
                <tr role="row">
                  <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                    aria-sort="ascending" aria-label="#">#</th>
                  <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Nama">
                    Nama</th>
                  <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Email">
                    Email</th>
                  <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Role">
                    Role</th>
                  <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Action">
                    Action</th>
                </tr>
              </thead>
              <tbody>
                @foreach ($users as $user)

                <tr role="row">
                  <td>{{$loop->iteration}}</td>
                  <td>{{$user->name}}</td>
                  <td>{{$user->email}}</td>
                  <td>{{$user->role->name}}</td>
                  <td><a class="btn btn-warning btn-sm" href="{{route('admin.user.edit',$user->id)}}">Edit</a>
                    <a href="{{route('admin.user.delete',$user->id)}}" class="btn btn-danger btn-sm">Hapus</a></td>
                </tr>
                @endforeach

              </tbody>
            </table>
          </div><!-- /.card-body -->
        </div>
        <!-- /.card -->

      </section>
      <!-- /.Left col -->
    </div>
    <!-- /.row (main row) -->
  </div><!-- /.container-fluid -->
</section>
@include('admin.user.modal_tambah')
<!-- /.content -->
@endsection
@section('script')
<script>
  $(function () {
    $("#example2").DataTable();
    $('#example1').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
  });
  
  $(document).ready(function(){
    $('#ajaxSubmit').click(function(e){
      e.preventDefault();
      $.ajaxSetup({
        headers: {
          'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
      });
      $.ajax({
        url: "{{route('admin.user.store')}}",
        method: "post",
        data: {
          'name': $('#name').val(),
          'email' : $('#email').val(),
          'password' : $('#password').val()
        },
        success: function(res){
          console.log(res);
          $('#modal-tambah').modal('toggle');
          toastr["success"](res.success, "Sukses");
        }
      })
    })
  })
  toastr.options = {
  "closeButton": true,
  "debug": false,
  "newestOnTop": false,
  "progressBar": true,
  "positionClass": "toast-top-right",
  "preventDuplicates": false,
  "onclick": null,
  "showDuration": "300",
  "hideDuration": "1000",
  "timeOut": "5000",
  "extendedTimeOut": "1000",
  "showEasing": "swing",
  "hideEasing": "linear",
  "showMethod": "fadeIn",
  "hideMethod": "fadeOut"
}

</script>
@endsection

resources/views/admin/user/tambah.blade.php
@extends('layouts.admin')
@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Dashboard</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item active">Dashboard v1</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <div class="col-lg-12 col-12">
        <div class="card">
          <div class="card-header border-1">
            <div class="d-flex justify-content-between align-items-center">
              <h3 class="card-title">Tambah Akun</h3>
              <a href="{{route('admin.user.index')}}" class="btn btn-info btn-sm">Batal</a>
            </div>
          </div>
          <div class="card-body">
            <form id='myForm'>
              @csrf
              <div class="form-group">
                <label for="noTelp">Nama</label>
                <input name="name" type="text" class="form-control" id="name" placeholder="Masukkan Nama Lengkap Anda">
              </div>
              <div class="form-group">
                <label for="email">Email</label>
                <input name="email" type="email" class="form-control" id="email" placeholder="Email">
              </div>
              <div class="form-group">
                <label for="password">Email</label>
                <input name="password" type="password" class="form-control" id="password" placeholder="Password">
              </div>
              <button class="btn btn-success float-right" id="ajaxSubmit">Tambah</button>
            </form>
          </div>
        </div>
      </div>
      <!-- /.col-md-6 -->
    </div>
    <!-- /.row (main row) -->
  </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection

@section('script')
<script>
  $(document).ready(function(){
    $('#ajaxSubmit').click(function(e){
      e.preventDefault();
      $.ajaxSetup({
        headers: {
          'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
      });
      $.ajax({
        url: "{{route('admin.user.store')}}",
        method: "post",
        data: {
          'name': $('#name').val(),
          'email' : $('#email').val(),
          'password' : $('#password').val()
        },
        success: function(res){
          console.log(res);
          toastr["success"](res.success, "Sukses")
        }
      })
    })
  })
  toastr.options = {
  "closeButton": true,
  "debug": false,
  "newestOnTop": false,
  "progressBar": true,
  "positionClass": "toast-top-right",
  "preventDuplicates": false,
  "onclick": null,
  "showDuration": "300",
  "hideDuration": "1000",
  "timeOut": "5000",
  "extendedTimeOut": "1000",
  "showEasing": "swing",
  "hideEasing": "linear",
  "showMethod": "fadeIn",
  "hideMethod": "fadeOut"
}
</script>

@endsection

resources/views/user/industri/daftar.blade.php
@extends('layouts.user')
@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Pendaftaran Industri</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">User</a></li>
                    <li class="breadcrumb-item"><a href="#">Industri</a></li>
                    <li class="breadcrumb-item active">Daftar</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Main row -->
        <div class="row">
            <!-- Left col -->
            <section class="col-lg-12 col-sm-12 col-12">
                {{-- kanan --}}
                <form method="POST" action="{{route('user.industri.save')}}">
                    @csrf
                    <div class="row">
                        <div class="col-lg-6 col-sm-12 col-6">
                            <div class="card">
                                {{-- <div class="card-header">
                            <h3 class="card-title">
                                Profil Industri
                            </h3>
                        </div><!-- /.card-header --> --}}
                                {{-- .card-body --}}
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="namaUsaha">Nama Usaha</label>
                                        <input type="text" name="nama_usaha" class="form-control" id="namaUsaha"
                                            placeholder="Nama Usaha">
                                    </div>
                                    <div class="form-group">
                                        <label for="namaPemilik">Nama Pemilik</label>
                                        <input name="nama_pemilik" type="text" class="form-control" id="namaPemilik"
                                            placeholder="Nama Pemilik">
                                    </div>
                                    <div class="form-group">
                                        <label for="nikPemilik">NIK Pemilik</label>
                                        <input name="nik" type="integer" class="form-control" id="nikPemilik"
                                            placeholder="NIK Pemilik">
                                    </div>
                                    <div class="form-group">
                                        <label for="alamatPemilik">Alamat Pemilik</label>
                                        <input name="alamat_pemilik" type="text" class="form-control" id="alamatPemilik"
                                            placeholder="Alamat Pemilik">
                                    </div>
                                    <div class="form-group">
                                        <label for="alamatUsaha">Alamat Usaha</label>
                                        <input name="alamat_usaha" type="text" class="form-control" id="alamatUsaha"
                                            placeholder="Alamat Usaha">
                                    </div>
                                </div>
                                {{-- /.card-body --}}
                            </div>
                            <!-- /.card -->
                        </div>
                        {{-- kiri --}}
                        <div class="col-lg-6 col-sm-12 col-6">
                            <div class="card">
                                {{-- <div class="card-header">
                            <h3 class="card-title">
                                Profil Industri
                            </h3>
                        </div><!-- /.card-header --> --}}

                                {{-- .card-body --}}
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="noTelp">No. Telepon</label>
                                        <input name="no_telp" type="text" class="form-control" id="noTelp"
                                            placeholder="No. Telepon">
                                    </div>
                                    <div class="form-group">
                                        <label for="noHp">No. HP</label>
                                        <input name="no_hp" type="text" class="form-control" id="noHp"
                                            placeholder="No. HP">
                                    </div>
                                    <div class="form-group">
                                        <label for="email">Email</label>
                                        <input name="email" type="email" class="form-control" id="email"
                                            placeholder="Email">
                                    </div>
                                    <div class="form-group">
                                        <label for="NPWP">NPWP</label>
                                        <input name="npwp" type="text" class="form-control" id="NPWP"
                                            placeholder="NPWP">
                                    </div>
                                    <div class="form-group">
                                        <label for="jenisUsaha">Jenis Usaha</label>
                                        <input name="jenis_usaha" type="text" class="form-control" id="jenisUsaha"
                                            placeholder="Jenis Usaha">
                                    </div>
                                </div>
                                {{-- /.card-body --}}
                            </div>
                            <!-- /.card -->
                        </div>
                    </div>
                    <input class="btn btn-info float-right" type="submit" value="Simpan" />
                </form>
            </section>
            <!-- /.Left col -->
            <div class="clear-fix"></div>

        </div>
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->

@endsection